# Generated by Django 5.0.7 on 2024-09-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=63)),
                ('verified', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='profile_picture')),
            ],
        ),
    ]
