# Generated by Django 5.0.7 on 2024-09-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
