# Generated by Django 5.0.7 on 2024-09-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/img/default_profile_picture.jpg', upload_to='profile_picture'),
        ),
    ]
