# Generated by Django 5.0.7 on 2024-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_vendor_date_of_join_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(default='Madarima', max_length=63),
        ),
    ]
