# Generated by Django 5.0.7 on 2024-07-28 11:41

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_vendor_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='cover_vendor.jpg', upload_to=store.models.user_directory_path),
        ),
    ]
