# Generated by Django 5.0.7 on 2024-07-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.CharField(default='365 Days', max_length=63),
        ),
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(default='12', max_length=63),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Organic', max_length=63),
        ),
    ]
