# Generated by Django 5.0.7 on 2024-07-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_life_alter_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
