# Generated by Django 5.0.7 on 2024-07-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
