# Generated by Django 5.0.7 on 2024-07-30 19:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_vendor_city_vendor_post_code_alter_vendor_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='This is the product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='I am a Cool Vendor', null=True),
        ),
    ]
