# Generated by Django 5.0.7 on 2024-08-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_productreview_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='product_status',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
    ]
