# Generated by Django 5.0.7 on 2024-08-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
