# Generated by Django 5.0.7 on 2024-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_address_state_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
