# Generated by Django 5.0.7 on 2024-09-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_cartorder_address_cartorder_city_cartorder_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
