# Generated by Django 5.0.7 on 2024-10-03 09:11

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_cartorder_saved_cartorder_shipping_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=63)),
                ('discount', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('uses', models.IntegerField()),
                ('use_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=22, max_length=5, prefix='', unique=True),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='pid',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='product_id',
            field=models.CharField(default=1, max_length=127),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='This is the product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, default='I am a Cool Vendor', null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='store.coupon'),
        ),
    ]
