# Generated by Django 5.0.7 on 2024-10-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_coupon_cartorder_oid_cartorderitems_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.CharField(default='100', max_length=63),
        ),
    ]
