# Generated by Django 5.0.7 on 2024-09-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_cartorder_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='use_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
