# Generated by Django 5.0.7 on 2024-09-17 11:30

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_coupon_use_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='oid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=2, max_length=30, prefix='', unique=True),
        ),
    ]
