# Generated by Django 5.0.7 on 2024-10-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_product_specifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecifications',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_specifications', to='store.product'),
        ),
    ]
