# Generated by Django 5.0.7 on 2024-09-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_cartorder_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='uses',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
    ]
