# Generated by Django 5.0.7 on 2024-11-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_address_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
