# Generated by Django 5.0.7 on 2025-01-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_product_stock_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
