# Generated by Django 5.0.7 on 2025-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_cartorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
