# Generated by Django 5.0.7 on 2024-09-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
