# Generated by Django 5.0.7 on 2025-03-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_phone_contactus_phone_number'),
        ('userauths', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauths.user'),
        ),
    ]
